Fix outline-promote/demote space issue and add extra-face support
alphapapa/outshine pull request #90
Opened 2021-12-29 23:04 UTC by jdtsmith

This PR fixes #63, which results from an unnecessary space being added directly into `outline-regexp`.  This space _is_ needed for proper font-locking, so it is included there.

Also included is a new customize variable `outshine-outline-extra-face`, which, if set can be used to configure the face of the _outline match_ itself (e.g. `;;;;`, `# ***`, etc.)  By adding `:overline` and `:extend` to the outshine faces, you can then achieve some good-looking separators.  Along the way, `outshine-headings-list` is generalized.

2021-12-29 23:11 UTC, jdtsmith commented
Here's an example of the new face configurability in use:

![image](https://user-images.githubusercontent.com/93749/147709776-a5d9a9fa-65a7-4e6a-80da-2b2cae00e270.png)

2022-05-02 12:36 UTC, alphapapa commented
Apparently I overlooked this PR for a while, until it appeared in my issues list again just now.  Please feel free to ping me in the future if I overlook it again (I don't work on this project very often).

I'll make some comments as a review.  Thanks for your work on this.

2022-05-02 12:39 UTC, alphapapa requested changes
Thanks.

2022-05-02 12:39 UTC, alphapapa commented on README.org
> +*Fixed*
Please rebase the branch.

2022-05-02 12:39 UTC, alphapapa commented on outshine.el
> +  "Extra face, faces, or face property lists(s) to use for the
Please follow the conventions regarding docstrings (i.e. a short first sentence that fits on one line, details in subsequent sentences and paragraphs, and the docstring should be indented according to Elisp conventions).  Use `M-x checkdoc` to help.

2022-05-02 12:39 UTC, alphapapa commented on outshine.el
> +  (let* ((outline-rgxp (substring outline-regexp 0 -7))
Nitpicky, but please don't further abbreviate `regexp` to `rgxp`.  The Emacs conventions that I know of are `regexp` and `re`.

2022-05-02 21:35 UTC, jdtsmith commented on outshine.el
> +  (let* ((outline-rgxp (substring outline-regexp 0 -7))
Fixed.  I actually stole this abbreviation from elsewhere in the file.  But I don't think I need to have both the lexical and global set for anything.  It also occurs to me that this substring method won't work for `outshine-max-level`>=10.  But that's been the case since outshine was created I think and hasn't caused issues.

2022-05-02 21:36 UTC, jdtsmith commented
> Apparently I overlooked this PR for a while, until it appeared in my issues list again just now. Please feel free to ping me in the future if I overlook it again (I don't work on this project very often).

Thanks no worries.  I've been using this branch for several months without problem.

2022-05-05 13:31 UTC, alphapapa commented
Thanks.  As a final step, if you would update the changelog in the readme and squash the branch, it could be merged directly then.

2022-05-05 22:58 UTC, jdtsmith commented
> Thanks. As a final step, if you would update the changelog in the readme and squash the branch, it could be merged directly then.

Done thanks.

2022-06-05 22:44 UTC, jdtsmith commented
@alphapapa: a ping, as requested.

2022-09-16 22:09 UTC, jdtsmith commented
Closing this in favor of my new much simpler mode [outli](https://github.com/jdtsmith/outli) which includes this type of styling by default.

2022-09-16 22:09 UTC, closed without merging